baseurl : "https://TeamMeltingPoppo.github.io/"
languageCode: "ja-jp"
title: "SwingBy's blog"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
enableEmoji: true
enableEmojiCDN: true
enableGitInfo: true
paginate: 10

taxonomies:
  category : "categories"
  tag : "tags"
  series : "series"
  archive : "archives"

menu:
  main:
    - name: 最新情報
      url: "/"
      weight: 1
    - name: 団体情報
      url: "about/"
      weight: 2
    - name: 班紹介
      url: "teams/"
      weight: 3
    - name: アクセス
      url: "access/"
      weight: 4
    - name: 支援
      url: "sponsor/"
      weight: 5
    - name: お問い合わせ
      url: "links/"
      weight: 6

params:
  social:
    twitter: "melting_poppo"
    github: "TeamMeltingPoppo"
  description: "SwingBy's blog"
  footer: "&copy; https://TeamMeltingPoppo.github.io \ 2024 -- {Year}"

markup:
  highlight:
    pygmentsCodefences : true
    style : "monokai"
  goldmark:
    renderer:
      unsafe: true


author.name : "SwingBy"
#author.photo : "img/avatar128x128.jpg" #include this if you would like to show the author photo on the sidebar